name: Validate Plugins

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate Plugin Configurations
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Run validation script
        id: validate
        run: python .github/scripts/validate-plugins.py
      
      - name: Summary
        if: always()
        run: |
          if [ "${{ steps.validate.outcome }}" = "success" ]; then
            echo "✅ All plugin validations passed!" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Plugin validation failed. Check the logs above for details." >> $GITHUB_STEP_SUMMARY
          fi
